### ISSUE TITLE
Propuesta de cambio en modelo para soportar cambio de nombre de interesados.

### ISSUE THREAD

**Issue by AlejoTellezF** [SwissTierrasColombia/LADM_COL#4]
Actualmente el modelo permite el almacenamiento del atributo nombre en las clases relacionadas con interesados; ya sea por medio del atributo "Razon_Social" de la clase "Interesado_Juridico", de los diferentes atributos concernientes al nombre en la clase "Interesado_Natural" o del atributo "Nombre" en la clase abstracta LA_Interesado. Pero en los casos en los que un interesado cambia su nombre o razón social, no existe una forma de asociar el nuevo nombre al registro del interesado en cuestión, ya que esto es posible mapearlo con el modelo actual, únicamente usando la herencia de la clase "ObjetoVersionado", lo que quiere decir crear un nuevo registro y finalizar la vida util del anterior. 

![image](https://user-images.githubusercontent.com/6115334/38510724-7cda9a20-3beb-11e8-963e-7038ad6f33c4.png)

Me parece que este comportamiento puede mejorarse, al asociar un interesado natural o juridico con una clase que contenga los datos del nombre del interesado y pueda guardar su histórico. Por lo tanto esta relación debe tener cardinalidad 1..* y la clase debe heredar de ObjetoVersionado, tal como se muestra a continuación:

![image](https://user-images.githubusercontent.com/6115334/38511970-6f3ed972-3bef-11e8-9bba-86ce1a478bb1.png)

De esta manera sería posible hacer cambios en el nombre del interesado, se tendría acceso a su histórico de cambios y siempre estarían asociados al mismo registro de Interesado sin tener que crear uno nuevo.

**Comment by aranguren** [comment]
Personalmente creo que es mejor dejarlo como objeto versionado directamente
las clases Interesado, ya que es más probable que cambien otros atributos
como fecha de emisión del documento, tipo de documento..que el nombre

**Comment by phybriso** [comment]
Al parecer el cambio sí ocurre más o menos de manera común, por lo menos para los interesados jurídicos, porque al haber una fusión o unión de empresas cambia la razón social pero se mantiene el Número del NIT. De ahí nació la idea de modelarlo de está manera, aunque también podría pensarse en aplicarlo únicamente para interesado jurídico
